# version: '3'
# services:
#   db:
#     image: postgres:latest
#     restart: always
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=budget
#     ports:
#       - "5432:5432"
#     volumes:
#       - my-db:/var/lib/postgres

#   go:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: /bin/sh -c "go run main.go"
#     volumes:
#       - .:/app
#     ports:
#       - 8080:8080
#     depends_on:
#       - db
# volumes:
#   my-db:

# Specify the version for docker-compose.yml
version: "3"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)
      # POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run ."
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  dbdata: # create the volume for persisting data.